In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("train_and_test2.csv")

In [4]:
df.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [5]:
print(df.columns.tolist())

['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1', 'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7', 'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13', 'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17', 'zero.18', '2urvived']

In [6]:
df = df[['Age', 'Fare', 'Sex', 'sibsp', 'Pclass', 'Embarked', '2urvived']]

In [7]:
df.head()

    Age     Fare  Sex  sibsp  Pclass  Embarked  2urvived
0  22.0   7.2500    0      1       3       2.0         0
1  38.0  71.2833    1      1       1       0.0         1
2  26.0   7.9250    1      0       3       2.0         1
3  35.0  53.1000    1      1       1       2.0         1
4  35.0   8.0500    0      0       3       2.0         0

In [8]:
df.isnull().sum()

Age         0
Fare        0
Sex         0
sibsp       0
Pclass      0
Embarked    2
2urvived    0
dtype: int64

In [9]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [10]:
df.isnull().sum()

Age         0
Fare        0
Sex         0
sibsp       0
Pclass      0
Embarked    0
2urvived    0
dtype: int64

In [13]:
import numpy as np
age_mean = np.mean(df['Age'])
age_median = np.median(df['Age'])
age_std = np.std(df['Age'])

print("Mean :", age_mean)
print("Median :", age_median)
print("Standard Deviation :", age_std)

Mean : 29.50318563789152
Median : 28.0
Standard Deviation : 12.900310216388611

In [14]:
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR 
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['Fare'] < lower_bound) | (df['Fare'] > upper_bound)]
print('Number Of Outliers : ',len(outliers))
print("Upper Bound : ", upper_bound)
outliers.head()

Number Of Outliers :  171
Upper Bound :  66.34379999999999

     Age      Fare  Sex  sibsp  Pclass  Embarked  2urvived
1   38.0   71.2833    1      1       1       0.0         1
27  19.0  263.0000    0      3       1       2.0         0
31  28.0  146.5208    1      1       1       0.0         1
34  28.0   82.1708    0      1       1       0.0         0
52  49.0   76.7292    1      1       1       0.0         1

In [16]:
df['Fare_log'] = np.log1p(df['Fare'])
df[['Fare','Fare_log']].head()

      Fare  Fare_log
0   7.2500  2.110213
1  71.2833  4.280593
2   7.9250  2.188856
3  53.1000  3.990834
4   8.0500  2.202765

In [17]:
df['Family_Size']= df['sibsp']+1
df[['sibsp', 'Family_Size']].head()

   sibsp  Family_Size
0      1            2
1      1            2
2      0            1
3      1            2
4      0            1

In [20]:
df.groupby('2urvived')['Age'].mean()

2urvived
0    29.931748
1    28.291433
Name: Age, dtype: float64